name: DotNet CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: dotnet test --verbosity normal