name: Build & Test On Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Unit tests
        run: dotnet test --filter "SshTools.Tests.Unit" --no-restore --verbosity normal
      - name: Integration tests
        run: dotnet test --filter "SshTools.Tests.Integration" --no-restore --verbosity normal